name: Abo Ali CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # prevent infinite runs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install -g pm2
          npm install
          cd ../frontend
          npm install
          cd ..

      # 🔹 Start backend in background and wait for it
      - name: Start backend
        run: |
          cd backend
          npm run dev &
          cd ..
          npx wait-on http://localhost:4000/status
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # 🔹 Start frontend in background and wait for it
      - name: Start frontend
        run: |
          cd frontend
          npm run dev &
          cd ..
          npx wait-on http://localhost:5173
        env:
          VITE_API_URL: http://localhost:4000

      # 🔹 Run backend tests
      - name: Run backend tests
        run: |
          cd backend
          npm test
          cd ..

      # 🔹 Check backend status endpoint
      - name: Test /status endpoint
        run: |
          RESPONSE=$(curl -s http://localhost:4000/status)
          echo "Response: $RESPONSE"
          if [[ "$RESPONSE" != *"OK"* ]]; then
            echo "Backend status check failed!"
            exit 1
          fi

      # 🔹 Run frontend Playwright tests
      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright install --with-deps
          npx playwright test
